### PR TITLE
Add Contribution overview

### PR DESCRIPTION
**Pull request by Aidenbuis**
- Added CONTRIBUTING.md
- Added All Contributors bot

### CODE REVIEW

**Comment by Aidenbuis** [comment]
@all-contributors please add 
@copebo for design, content and userTesting, a11y
@Kingmar1 for code
@Swendude for code
@EVerhaar for maintenance, content, userTesting
@BernardVuijk for projectManagement
@ericherman for mentoring
@HagenaarC for business
@JasonKAEC for code, a11y, test, doc
@Paulien-Wan for test
@Aidenbuis for code, a11y, test, doc

**Comment by Aidenbuis** [comment]
@all-contributors please add @Aidenbuis for code, a11y, test, doc

**Comment by Aidenbuis** [comment]
@all-contributors please add @copebo for design, content and userTesting, a11y
@all-contributors please add @Kingmar1 for code
@all-contributors please add @Swendude for code
@all-contributors please add @EVerhaar for maintenance, content, userTesting
@all-contributors please add @BernardVuijk for projectManagement
@all-contributors please add @ericherman for mentoring
@all-contributors please add @HagenaarC for business
@all-contributors please add @JasonKAEC for code, a11y, test, doc
@all-contributors please add @Paulien-Wan for test

**Comment by Aidenbuis** [comment]
@all-contributors please add @copebo for design, content and userTesting, a11y

**Comment by Aidenbuis** [comment]
@all-contributors please add @Kingmar1 for code

**Comment by Aidenbuis** [comment]
@all-contributors please add @Swendude for code

**Comment by Aidenbuis** [comment]
@all-contributors please add @EVerhaar for maintenance, content, userTesting

**Comment by Aidenbuis** [comment]
@BernardVuijk for projectManagement

**Comment by Aidenbuis** [comment]
@all-contributors please add @BernardVuijk for projectManagement

**Comment by Aidenbuis** [comment]
@all-contributors please add @ericherman for mentoring

**Comment by Aidenbuis** [comment]
@all-contributors please add @HagenaarC for business

**Comment by Aidenbuis** [comment]
@all-contributors please add @JasonKAEC for code, a11y, test, doc

**Comment by Aidenbuis** [comment]
@all-contributors please add @Paulien-Wan for test

**Review by ericherman — COMMENTED** [review]
Nice.

**Pull request merged**
